DROP SCHEMA IF EXISTS `salesManager`;
CREATE SCHEMA IF NOT EXISTS `salesManager`;
USE `salesManager`;


-- THÔNG TIN TÀI KHOẢN
DROP TABLE IF EXISTS `USER`;
CREATE TABLE IF NOT EXISTS `USER` (
	`USER_ID` BIGINT AUTO_INCREMENT NOT NULL,
	`LAST_NAME` NVARCHAR(40) NOT NULL,
	`FIRST_NAME` NVARCHAR(10) NOT NULL,
	`GENDER` NVARCHAR(5) NULL DEFAULT 'Khác',						-- NAM, NỮ, KHÁC
	`DATE_OF_BIRTH` DATE NULL,										-- NGÀY SINH
    
    `PHONE_NUMBER` VARCHAR(15) NULL,
    `EMAIL` VARCHAR(40) NULL,
    `IMAGE` LONGTEXT DEFAULT NULL,									-- BASE64 IMAGE
    
	`USER_NAME` VARCHAR(40) NOT NULL,
	`PASSWORD` VARCHAR(32) NOT NULL,
    `USER_TYPE` VARCHAR(15) DEFAULT 'CUSTOMER' NOT NULL,			-- ADMIN, EMPLOYEE, CUSTOMER
    
	`STATUS` TINYINT(1) DEFAULT '1',								-- TRẠNG THÁI
    
    PRIMARY KEY(`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;